// <auto-generated />
namespace ListaDeTarefas.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ddmmyyyyid : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ddmmyyyyid));
        
        string IMigrationMetadata.Id
        {
            get { return "201803050222397_dd-mm-yyyy-id"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
